version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swift-api-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=swiftuser
      - DB_PASSWORD=mikus123
      - DB_NAME=swift
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: swift-api-db
    restart: always
    environment:
      POSTGRES_USER: swiftuser
      POSTGRES_PASSWORD: mikus123
      POSTGRES_DB: swift
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swiftuser -d swift"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
