version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swift-api-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=swiftuser
      - DB_PASSWORD=mikus123
      - DB_NAME=swift
    ports:
      - "8080:8080" # Aplikacja dostępna na localhost:8080
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: swift-api-db
    restart: always
    environment:
      POSTGRES_USER: swiftuser
      POSTGRES_PASSWORD: mikus123
      POSTGRES_DB: swift
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # Zachowanie danych między restartami kontenera
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
